// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odev3_API.Models;

namespace Odev_3API.Migrations
{
    [DbContext(typeof(ObsDbContext))]
    [Migration("20221209175811_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DersOgrenci", b =>
                {
                    b.Property<Guid>("DerslerDersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OgrencilerOgrenciNo")
                        .HasColumnType("int");

                    b.HasKey("DerslerDersId", "OgrencilerOgrenciNo");

                    b.HasIndex("OgrencilerOgrenciNo");

                    b.ToTable("DersOgrenci");
                });

            modelBuilder.Entity("Odev3_API.Models.Akademisyen", b =>
                {
                    b.Property<Guid>("AkademisyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AkademisyenAd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("İsim");

                    b.Property<string>("AkademisyenSoyad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Soyisim");

                    b.Property<long>("AkademisyenTC")
                        .HasMaxLength(11)
                        .HasColumnType("bigint")
                        .HasColumnName("T.C. Kimlik No");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AnabilimDali")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Anabilim Dalı");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("date")
                        .HasColumnName("Doğum Tarihi");

                    b.Property<string>("EPosta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UptatedBy")
                        .HasColumnType("int");

                    b.HasKey("AkademisyenId");

                    b.ToTable("Akademisyenler");
                });

            modelBuilder.Entity("Odev3_API.Models.Ders", b =>
                {
                    b.Property<Guid>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(25)
                        .HasColumnType("text")
                        .HasColumnName("Açıklama");

                    b.Property<int>("AkademisyenId")
                        .HasColumnType("int");

                    b.Property<Guid?>("AkademisyenId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ders Adı");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Ders Kodu");

                    b.Property<string>("Derslik")
                        .HasMaxLength(10)
                        .HasColumnType("text");

                    b.Property<string>("Donem")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Dönem");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<short>("KacSaat")
                        .HasColumnType("smallint")
                        .HasColumnName("Ders Saati");

                    b.Property<short>("Kredi")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UptatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("ZorunluMu")
                        .HasColumnType("bit");

                    b.HasKey("DersId");

                    b.HasIndex("AkademisyenId1");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("Odev3_API.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Bölüm");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("date")
                        .HasColumnName("Doğum Tarihi");

                    b.Property<string>("EPosta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OgrenciAd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("İsim");

                    b.Property<string>("OgrenciSoyad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Soyisim");

                    b.Property<long>("OgrenciTC")
                        .HasMaxLength(11)
                        .HasColumnType("bigint")
                        .HasColumnName("T.C. Kimlik No");

                    b.Property<string>("Sinif")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Sınıf");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UptatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UptatedBy")
                        .HasColumnType("int");

                    b.HasKey("OgrenciNo")
                        .HasName("Öğrenci No");

                    b.ToTable("Öğrenci");
                });

            modelBuilder.Entity("DersOgrenci", b =>
                {
                    b.HasOne("Odev3_API.Models.Ders", null)
                        .WithMany()
                        .HasForeignKey("DerslerDersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odev3_API.Models.Ogrenci", null)
                        .WithMany()
                        .HasForeignKey("OgrencilerOgrenciNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Odev3_API.Models.Ders", b =>
                {
                    b.HasOne("Odev3_API.Models.Akademisyen", "Akademisyen")
                        .WithMany("Dersler")
                        .HasForeignKey("AkademisyenId1");

                    b.Navigation("Akademisyen");
                });

            modelBuilder.Entity("Odev3_API.Models.Akademisyen", b =>
                {
                    b.Navigation("Dersler");
                });
#pragma warning restore 612, 618
        }
    }
}
